### ISSUE TITLE
No deja importar el data-20150815.json

### ISSUE THREAD

**Issue by johnfelipe** [YoQuieroSaber/votai-theme#60]
```
(votainteligente)notroot@dhcppc3:~/votainteligente-portal-electoral$ ./manage. loaddata data-20150815.json
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 147, in load_label
    obj.save(using=self.using)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save_base
    update_fields=update_fields)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/src/django-popolo/popolo/models.py", line 477, in validate_date_fields
    obj.full_clean()
  File "/home/notroot/votainteligente-portal-electoral/votainteligente/local/lib/python2.7/site-packages/django/db/models/base.py", line 1147, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'start_date': [u'Date has wrong format', u'date seems not to be correct 25/07/1947']}
```

**Comment by martinszy** [comment]
No termino de entender el error, ya que el dato "25/07/1947" está en el campo "birth_date", que no tiene validación de fechas, como se puede ver aquí: https://github.com/openpolis/django-popolo/blob/master/popolo/models.py#L50

El campo start_date si tiene validación de fecha, pero está vacío en todos los casos.

Te sugiero que elimines el archivo, lo descargues de nuevo y vuelvas a probar.

**Comment by martinszy** [comment]
Encontramos un work-around: eliminar todos los valores de birth_date.
Por ejemplo, usar una regular expression que sea birth_date=".*" para reemplazar por birth_date=""
